const API='../backend/api/admin.php';
const $=id=>document.getElementById(id);
async function api(action, options={}){const r=await fetch(`${API}?action=${action}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({success:false,message:'Invalid server response'}));if(r.status===401){location.href='index.php';}return d;}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
function money(v){return '₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function badge(v){return `<span class="badge ${String(v).toLowerCase()}">${String(v).replaceAll('_',' ')}</span>`}
if($('loginForm')){$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('error').textContent='Signing in…';const d=await api('login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});if(d.success)location.href='dashboard.php';else $('error').textContent=d.message||'Login failed';});}
async function loadMe(){const d=await api('me');if(d.success)$('adminUser').textContent=`${d.admin.name} · ${d.admin.email}`}
async function loadDashboard(){const d=await api('stats');if(!d.success)return;$('stats').innerHTML=[['Cars',d.stats.cars],['Available',d.stats.available_cars],['Bookings',d.stats.bookings],['Revenue',money(d.stats.revenue)],['Customers',d.stats.customers],['Pending Payments',d.stats.pending_payments],['Confirmed',d.stats.confirmed],['Fleet Utilization',d.stats.cars?Math.round((d.stats.cars-d.stats.available_cars)/d.stats.cars*100)+'%':'0%']].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');$('recent').innerHTML=d.recent.map(r=>`<tr><td>${r.booking_code}</td><td>${r.customer_name}<br><small>${r.customer_phone}</small></td><td>${r.car_name}</td><td>${money(r.total_amount)}</td><td>${badge(r.booking_status)}</td><td>${badge(r.payment_status)}</td></tr>`).join('')||'<tr><td colspan="6">No bookings yet.</td></tr>'}
async function loadCars(){const d=await api('cars');if(!d.success)return;$('carsTable').innerHTML=d.cars.map(c=>`<tr><td><b>${c.name}</b></td><td>${c.category}</td><td>${money(c.price_per_hour)}</td><td>${c.fuel}</td><td>${c.seats}</td><td>${badge(c.status)}</td><td><button class="action" onclick='openCar(${JSON.stringify(c)})'>Edit</button><button class="action" onclick="deactivateCar(${c.id})">Deactivate</button></td></tr>`).join('')}
function openCar(c=null){$('modal').classList.add('show');$('modalTitle').textContent=c?'Edit Car':'Add Car';$('carId').value=c?.id||'';$('carName').value=c?.name||'';$('category').value=c?.category||'suv';$('price').value=c?.price_per_hour||'';$('fuel').value=c?.fuel||'Petrol';$('transmission').value=c?.transmission||'Automatic';$('seats').value=c?.seats||5;$('image').value=c?.image||'';$('carStatus').value=c?.status||'available'}
function closeModal(){$('modal').classList.remove('show')}
$('carForm')?.addEventListener('submit',async e=>{e.preventDefault();const payload={op:'save',id:Number($('carId').value)||0,name:$('carName').value,category:$('category').value,price_per_hour:Number($('price').value),fuel:$('fuel').value,transmission:$('transmission').value,seats:Number($('seats').value),image:$('image').value,status:$('carStatus').value};const d=await api('cars',{method:'POST',body:JSON.stringify(payload)});if(d.success){closeModal();toast(d.message);loadCars();loadDashboard()}else toast(d.message||'Could not save car')});
async function deactivateCar(id){if(!confirm('Deactivate this car?'))return;const d=await api('cars',{method:'POST',body:JSON.stringify({op:'delete',id})});toast(d.message||'Updated');loadCars();loadDashboard()}
async function loadBookings(){const d=await api('bookings');if(!d.success)return;$('bookingsTable').innerHTML=d.bookings.map(b=>`<tr><td><b>${b.booking_code}</b><br><small>${b.customer_phone}</small></td><td>${b.customer_name}<br>${b.pickup_location}</td><td>${b.car_name}</td><td>${b.pickup_datetime || b.pickup_date}<br>to ${b.return_datetime || b.return_date}</td><td>${money(b.total_amount)}</td><td>${badge(b.payment_status)}${b.transaction_id?`<br><small>${b.transaction_id}</small>`:''}</td><td><select class="status-select" onchange="updateBooking(${b.id},this.value)">${['pending_payment','confirmed','cancelled','completed'].map(s=>`<option value="${s}" ${s===b.booking_status?'selected':''}>${s.replaceAll('_',' ')}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="7">No bookings.</td></tr>'}
async function updateBooking(id,status){const d=await api('bookings',{method:'POST',body:JSON.stringify({id,booking_status:status})});toast(d.message||'Updated');loadDashboard();loadBookings()}
async function updatePaymentStatus(id,status){const d=await api('payment_status',{method:'POST',body:JSON.stringify({id,payment_status:status})});toast(d.message||'Updated');loadPayments();loadBookings();loadDashboard()}
async function loadPayments(){const d=await api('payments');if(!d.success)return;$('paymentsTable').innerHTML=d.payments.map(p=>`<tr><td><b>${p.transaction_id}</b></td><td>${p.booking_code}</td><td>${p.customer_name}</td><td>Cash at Pickup</td><td>${money(p.amount)}</td><td><select class="payment-status-select" onchange="updatePaymentStatus(${p.id},this.value)">${['pending','paid','failed','refunded'].map(s=>`<option value="${s}" ${s===p.payment_status?'selected':''}>${s.replaceAll('_',' ')}</option>`).join('')}</select><br>${badge(p.payment_status)}</td><td>${p.paid_at||p.created_at}</td></tr>`).join('')||'<tr><td colspan="7">No payments.</td></tr>'}
document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));$(btn.dataset.section).classList.add('active');$('title').textContent=btn.textContent; if(btn.dataset.section==='dashboard')loadDashboard();if(btn.dataset.section==='cars')loadCars();if(btn.dataset.section==='bookings')loadBookings();if(btn.dataset.section==='payments')loadPayments()}));
$('logout')?.addEventListener('click',async()=>{await api('logout',{method:'POST'});location.href='index.php'});
if($('adminUser')){loadMe();loadDashboard()}
